version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    container_name: flask-container

volumes:
  pgdata:
